name: docs

on:
  workflow_run:
    workflows: ["release"]
    types:
      - requested

  pull_request:
    types: [closed]
    branches:
    - master
    paths:
    - 'docs/**'

  push:
    paths:
    - 'docs/**'

jobs:

  doc:

    runs-on: ubuntu-latest

    steps:
      - name: Fake
        run: echo "docs"
