name: release

on:
  release:
    types: [published]


jobs:

  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Fake
        run: echo "codecov"

  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Fake
        run: echo "pypi"
