name: release

on:
  release:
    types: [published]


jobs:

  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Fake
        run: echo "codecov"

  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: pip3 install --upgrade setuptools wheel twine

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ '__token__' }}
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python3 setup.py sdist bdist_wheel
        twine upload --repository testpypi dist/*
